### ISSUE TITLE
Notebook for collating different steps for post #1

### ISSUE THREAD

**Issue by sayakpaul** [deep-diver/Model-Training-as-a-CI-CD-System#2]
@deep-diver I can work on a notebook that could basically enumerate all the steps we are following to cover the first part:

* Create a simple image with KFP that is used to create the template. 
* Mention that for the first time when the code is committed GitHub Actions will run the entire thing. 
* Clone this repository and commit a minimal change to the `example/my-pipeline/` to trigger a run. 

Let me know your thoughts and we can proceed accordingly.

**Comment by deep-diver** [comment]
@sayakpaul 

Good idea. Let's do that
But first of all, `example/my-pipeline/` was named for a experimental purpose, so we might have to change the name.

**Comment by sayakpaul** [comment]
Sure. Do you want to change the name? I can then start the notebook work.

**Comment by sayakpaul** [comment]
@deep-diver https://github.com/deep-diver/Model-Training-as-a-CI-CD-System/pull/3
